ZVV-Web-Lab-1/Controllers/AdminController.cs
using System.Web.Mvc;
using DAL_ZVV.Interfaces;
using DAL_ZVV.Entities;
using DAL_ZVV.Repositories;
using System.Web;

namespace ZVV_Web_Lab_1.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private IRepository<LabGlassware> repository;

        public AdminController(IRepository<LabGlassware> repo)
        {
            repository = repo;
        }

        public AdminController()
        {
            repository = new EFLabGWRepository(new ApplicationDbContext());
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(repository.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(LabGlassware lgw,
             HttpPostedFileBase imageUpload = null)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload != null)
                {
                    int count = imageUpload.ContentLength;
                    lgw.GW_Picture = new byte[count];
                    imageUpload.InputStream.Read(lgw.GW_Picture, 0, count);
                    lgw.GW_MIMEType = imageUpload.ContentType;
                }
                try
                {
                    repository.Update(lgw);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(lgw);
                }
            }
            else return View(lgw);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new LabGlassware());
        }

        [HttpPost]
        public ActionResult Create(LabGlassware lgw, 
            HttpPostedFileBase imageUpload = null)
        {
            if (ModelState.IsValid)
            {
                if (imageUpload != null && imageUpload.ContentLength < 100)
                {
                    int count = imageUpload.ContentLength;
                    lgw.GW_Picture = new byte[count];
                    imageUpload.InputStream.Read(lgw.GW_Picture, 0, count);
                    lgw.GW_MIMEType = imageUpload.ContentType;
                }
                try
                {
                    repository.Create(lgw);
                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(lgw);
                }
            }
            else return View(lgw);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(repository.Get(id));
        }

        [HttpPost]
        public ActionResult Delete(LabGlassware lgw)
        {
            try
            {
                repository.Delete(lgw.GW_ID);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(lgw);
            }
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.GetAll());
        }
    }
}

ZVV-Web-Lab-1/Controllers/GWController.cs
using System.Linq;
using System.Web.Mvc;
using DAL_ZVV.Entities;
using DAL_ZVV.Interfaces;
using DAL_ZVV.Repositories;
using System.Collections.Generic;
using ZVV_Web_Lab_1.Models;
using System.Threading.Tasks;

namespace ZVV_Web_Lab_1.Controllers
{
    public class GWController : Controller
    {
        private IRepository<LabGlassware> repository;
        private readonly int PageSize = 3;

        public GWController(IRepository<LabGlassware> repo)
        {
            repository = repo;
        }

        public GWController()
        {
            repository = new EFLabGWRepository(new ApplicationDbContext());
        }

        public ActionResult List(string group, int page = 1)
        {
            IEnumerable<LabGlassware> lst = repository
                .GetAll().Where(d => group == null || d.GW_Type.Equals(group))
                .OrderBy(d => d.GW_Price);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", 
                    PageListViewModel<LabGlassware>.CreatePage(lst, page, PageSize));
            }
            return View(PageListViewModel<LabGlassware>.CreatePage(lst, page, PageSize));
        }

        [HttpGet]
        public async Task<FileContentResult> GetImage(int id)
        {
            LabGlassware lgw = await repository.GetAsync(id);
            if (lgw != null)
            {
                return new FileContentResult(lgw.GW_Picture, lgw.GW_MIMEType);
            }
            else return null;
        }
    }
}

ZVV-Web-Lab-1/Views/Admin/Create.cshtml
@model DAL_ZVV.Entities.LabGlassware

@{
    ViewBag.Title = "Создать новый";
    ViewBag.LabNumber = "7";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Admin", FormMethod.Post,
        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GW_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GW_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GW_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GW_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Выберите файл", htmlAttributes: new { @class = "control-label col-md2" })
            <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                @if (Model.GW_Picture == null)
                {<p>Нет изображения</p>}
                else
                {
                    <img width="150" height="150"
                         src="@Url.Action("GetImage", "GW", new {id=Model.GW_ID })" class="img-thumbnail">
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

ZVV-Web-Lab-1/Views/Admin/Delete.cshtml
@model DAL_ZVV.Entities.LabGlassware

@{
    ViewBag.Title = "Удаление";
    ViewBag.LabNumber = "7";
}

<h2>@ViewBag.Title</h2>

<h3>Вы действительно желаете удалить?</h3>
<div>
    <hr />

    @using (Html.BeginForm("Delete", "Admin", Model , FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.GW_Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GW_Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GW_Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GW_Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GW_Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GW_Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.GW_Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GW_Price)
            </dd>
        </dl>

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

ZVV-Web-Lab-1/Views/Admin/Edit.cshtml
@model DAL_ZVV.Entities.LabGlassware
@{
    ViewBag.Title = "Редактирование";
    ViewBag.LabNumber = "7";
}
<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Edit", "Admin", FormMethod.Post,
        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Стеклянная посуда</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GW_ID)
        <div class="form-group">
            @Html.LabelFor(model => model.GW_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GW_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GW_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GW_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GW_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GW_Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Выберите файл", htmlAttributes: new { @class = "control-label col-md2" })
            <div class="col-md-10">
                <input type="file" name="imageUpload" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                @if (Model.GW_Picture == null)
                {<p>Нет изображения</p>}
                else
                {
                    <img width="150" height="150"
                         src="@Url.Action("GetImage", "GW", new {id=Model.GW_ID })" class="img-thumbnail">
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/MyScript.js"></script>
}

ZVV-Web-Lab-1/Views/Admin/Index.cshtml
@using DAL_ZVV.Entities
@model IEnumerable<LabGlassware>

@{
    ViewBag.Title = "Список";
    ViewBag.LabNumber = "7";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GW_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GW_Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GW_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GW_Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GW_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GW_Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GW_Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GW_Price)
        </td>
        <td>
            @Html.ActionLink("Удалить", "Delete", new { id = item.GW_ID })
            @Html.ActionLink("Редактировать", "Edit", new { id = item.GW_ID })
        </td>
    </tr>
}

</table>